.TH TAG 1 "July 2025" "1.0" "Tag Command Manual"
.SH NAME
tag \- A tool for manipulating and querying file tags

.SH SYNOPSIS
.B tag
[\fIoptions\fR] 
.BR \-a ", " \-\-add " <tags> <path>" 
.BR \-r ", " \-\-remove " <tags> <path>" 
.BR \-s ", " \-\-set " <tags> <path>" 
.BR \-m ", " \-\-match " <tags> <path>" 
.BR \-f ", " \-\-find " <tags> <path>" 
.BR \-u ", " \-\-usage " <tags> <path>" 
.BR \-l ", " \-\-list " <tags> <path>" 
.RI [options] " ..."

.SH DESCRIPTION
The \fBtag\fR command allows users to manipulate and query file tags. A \fItag\fR is a label associated with a file, which can be used to categorize and identify files.

.TP
\fItags\fR
A comma-separated list of tag names. Use \fI*\fR to match any tag, but it will not match files without tags.

.SH COMMANDS
The following commands are available for manipulating tags on files:

.TP
.B \-a, \-\-add
Add specified tags to the given file. Example: 
.br
tag -a "tag1,tag2" /path/to/file

.TP
.B \-r, \-\-remove
Remove specified tags from the given file. Example:
.br
tag -r "tag1" /path/to/file

.TP
.B \-s, \-\-set
Set (replace) the tags on a file with the specified tags. Example:
.br
tag -s "newtag1,newtag2" /path/to/file

.TP
.B \-m, \-\-match
Display files that have matching tags. Example:
.br
tag -m "tag1"

.TP
.B \-f, \-\-find
Find all files with specified tags, ignoring other options like \-A, -e, -R. Example:
.br
tag -f "tag2"

.TP
.B \-u, \-\-usage
Display information on tag usage. 

.TP
.B \-l, \-\-list
List the tags associated with the specified file. Example:
.br
tag -l /path/to/file

.SH OPTIONS
Additional options that modify the behavior of the command:

.TP
.B \-v, \-\-version
Output the version information of the tool.

.TP
.B \-h, \-\-help
Show a help message with a brief description of the commands and options.

.TP
.B \-A, \-\-all
Include invisible files while enumerating.

.TP
.B \-e, \-\-enter
Enter and enumerate the specified directories.

.TP
.B \-R, \-\-recursive
Process directories recursively.

.TP
.B \-n, \-\-name
Enable the display of filenames in output (default behavior).

.TP
.B \-N, \-\-no-name
Disable the display of filenames in output for list, find, match commands.

.TP
.B \-t, \-\-tags
Enable the display of tags in output for find, match commands.

.TP
.B \-T, \-\-no-tags
Disable the display of tags in output for list command.

.TP
.B \-g, \-\-garrulous
Show tags each on a new line (for list, find, match).

.TP
.B \-G, \-\-no-garrulous
Display tags in a comma-separated format after the filename (default).

.TP
.B \-c, \-\-color
Enable colored output for tag names.

.TP
.B \-p, \-\-slash
Terminate each directory name with a trailing slash.

.TP
.B \-0, \-\-null
Terminate output lines with NUL (\0) for compatibility with `xargs -0`.

.TP
.B \-\-home
Search for tagged files in the user's home directory.

.TP
.B \-\-local
Search for tagged files in the home and local filesystems.

.TP
.B \-\-network
Search for tagged files across home, local, and network filesystems.

.SH EXAMPLES
.TP
Add tags to a file:
.br
.B tag -a "project1,urgent" "/path/to/file"

.TP
List tags of a file:
.br
.B tag -l "/path/to/file"

.TP
Find all files with a specific tag:
.br
.B tag -f "tag_name"

.SH BUGS
For bug reports, please visit the [issue tracker](https://github.com/jdberry/tag/issues).

.SH AUTHOR
James Berry

.SH SEE ALSO
For more information, check out the official documentation or `man` pages for related commands.
